---
name: gluware.configure_port
runner_type: python-script
description: Configure a port (PoE enable/disable) via Gluware API
enabled: true
entry_point: configure_port.py
parameters:
  serial:
    type: string
    required: true
  port_id:
    type: string
    required: true
  poe_enabled:
    type: boolean
    required: true
  api_url:
    type: string
    required: false
    default: "http://wingpy:8080"
  api_key:
    type: string
    required: false
    secret: true
