version: '3.8'

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-reverse-proxy
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - proxy-net
      - netbox-docker_default
      - withpostgresandworker_default
    restart: unless-stopped
    depends_on:
      - ssl-cert-generator
      
  ssl-cert-generator:
    image: alpine/openssl
    container_name: ssl-cert-gen
    volumes:
      - ./ssl:/certs
    command: >
      sh -c "
        if [ ! -f /certs/nginx.crt ]; then
          openssl req -x509 -newkey rsa:4096 -keyout /certs/nginx.key -out /certs/nginx.crt -days 365 -nodes -subj '/C=US/ST=Local/L=Local/O=Nginx/OU=Proxy/CN=172.30.133.89'
          chmod 600 /certs/nginx.key
          chmod 644 /certs/nginx.crt
          echo 'SSL certificates generated'
        else
          echo 'SSL certificates already exist'
        fi
      "

networks:
  proxy-net:
    driver: bridge
  netbox-docker_default:
    external: true
  withpostgresandworker_default:
    external: true